name: friendbook
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # -----------------------------
  # ðŸ”¥ Firebase Dependencies
  # -----------------------------
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_analytics: ^10.10.7

  # -----------------------------
  # ðŸ”¥ State Management
  # -----------------------------
  provider: ^6.1.2

  # -----------------------------
  # ðŸ”¥ Utilities
  # -----------------------------
  intl: ^0.19.0
  image_picker: ^1.1.2
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
